name: CommonMark Specs

on: [push, pull_request]

jobs:
  specs:
    name: Run CommonMark specs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: cataggar/ghr/actions/install@ab95a8ea0632291f6b2a1ec0a7e81b11ec8ac01b
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          tools: cataggar/zig@v0.17.0 RWSGOq2NVecA2UPNdBUZykf1CCb147pkmdtYxgb3Ti+JO/wCYvhbAb/U
      - run: zig build -Dno-cli=true spec
